dist: trusty
sudo: required

services:
  - docker

install:
  # Build image
  - docker build -t shankarps/java-ftp-server .
  # Test that the instance can run (can be improved)
  - docker run --name ftp -p 21:21 shankarps/java-ftp-server ls -l 
